# Generated by Django 5.2.5 on 2025-08-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='unit',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='rank',
        ),
        migrations.AddField(
            model_name='candidate',
            name='paper',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
