# Generated by Django 5.2.5 on 2025-08-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_rename_unit_candidate_category_remove_candidate_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
