# Generated by Django 5.2.5 on 2025-08-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_candidate_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='rank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='marks_awarded',
            field=models.IntegerField(default=0),
        ),
    ]
