# Generated by Django 5.2.5 on 2025-08-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_candidate_viva_practical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
