# Generated by Django 5.2.5 on 2025-09-01 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_answer_answer_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_text',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='marks_awarded',
            new_name='marks_obt',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='army_number',
            new_name='army_no',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='practical_marks',
            new_name='credits',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='rank',
            new_name='duration_of_qualification',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='viva_marks',
            new_name='nsqf_level',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='category',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='question',
            name='number',
        ),
        migrations.AddField(
            model_name='candidate',
            name='adhaar_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='name_of_qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='practical_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='practical_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='s_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='training_center',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='viva_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='viva_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='exam_type',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default='primary', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='max_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.candidate'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
