# Generated by Django 5.2.5 on 2025-09-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_rename_answer_text_answer_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
