# Generated by Django 5.2.5 on 2025-09-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_alter_candidate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='trade',
            field=models.CharField(blank=True, choices=[('TTC', 'TTC'), ('OCC', 'OCC'), ('DTMN', 'DTMN'), ('EFS', 'EFS'), ('DVM', 'DVM'), ('LMN', 'LMN'), ('CLK SD', 'CLK SD'), ('STEWARD', 'STEWARD'), ('WASHERMAN', 'WASHERMAN (HOUSE KEEPER)'), ('CHEFCOM', 'CHEFCOM (MESS KEEPER)'), ('SKT', 'SKT'), ('MUSICIAN', 'MUSICIAN'), ('ARTSN WW', 'ARTSN WW'), ('HAIR DRESSER', 'HAIR DRESSER'), ('SP STAFF', 'SP STAFF')], max_length=50, null=True),
        ),
    ]
