# Generated by Django 5.2.5 on 2025-09-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_candidate_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='rank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='trade',
            field=models.CharField(blank=True, choices=[('TTC', 'TTC'), ('OCC', 'OCC'), ('DTMN', 'DTMN'), ('EFS', 'EFS'), ('DVM', 'DVM'), ('LMN', 'LMN'), ('CLK SD', 'CLK SD'), ('STEWARD', 'STEWARD'), ('WASHERMAN', 'WASHERMAN'), ('CHEFCOM', 'CHEFCOM'), ('HOUSE KEEPER', 'HOUSE KEEPER'), ('MESS KEEPER', 'MESS KEEPER'), ('SKT', 'SKT'), ('MUSICIAN', 'MUSICIAN'), ('ARTSN WW', 'ARTSN WW'), ('HAIR DRESSER', 'HAIR DRESSER'), ('SP STAFF', 'SP STAFF')], max_length=50, null=True),
        ),
    ]
