# Generated by Django 5.2.5 on 2025-09-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_candidate_rank_alter_candidate_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='center',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
