# Generated by Django 5.2.5 on 2025-09-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_candidate_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='center',
            field=models.CharField(blank=True, choices=[('Jaipur', 'Jaipur'), ('Hissar', 'Hissar'), ('Bathinda', 'Bathinda'), ('Sriganganagar', 'Sriganganagar'), ('Bikaner', 'Bikaner'), ('Suratgarh', 'Suratgarh'), ('Kota', 'Kota'), ('Port Blair', 'Port Blair'), ('Ahmednagar', 'Ahmednagar'), ('Bangalore', 'Bangalore'), ('Chennai', 'Chennai'), ('Pune MINTSD', 'Pune MINTSD'), ('MCTE Mhow', 'MCTE Mhow'), ('Secunderabad', 'Secunderabad'), ('Jhansi', 'Jhansi'), ('Ahmedabad', 'Ahmedabad'), ('Jodhpur', 'Jodhpur'), ('Saugor', 'Saugor'), ('Bhopal', 'Bhopal'), ('Pune', 'Pune'), ('Binaguri', 'Binaguri'), ('Kolkata', 'Kolkata'), ('Missamari', 'Missamari'), ('Rangapahar', 'Rangapahar'), ('Dinjan', 'Dinjan'), ('Gangtok', 'Gangtok'), ('Leimakhong', 'Leimakhong'), ('Tenga', 'Tenga'), ('Panagarh', 'Panagarh'), ('Ranchi', 'Ranchi'), ('Likabali', 'Likabali'), ('Tejpur', 'Tejpur'), ('Kalimpong', 'Kalimpong'), ('Jalandhar', 'Jalandhar'), ('Ambala', 'Ambala'), ('Delhi', 'Delhi'), ('Amritsar', 'Amritsar'), ('Ferozepur', 'Ferozepur'), ('Patiala', 'Patiala'), ('Jammu', 'Jammu'), ('Pathankot', 'Pathankot'), ('Chandimandir', 'Chandimandir'), ('Meerut', 'Meerut'), ('Agra', 'Agra'), ('Bareilly', 'Bareilly'), ('Jabalpur', 'Jabalpur'), ('Lucknow', 'Lucknow'), ('Ranikhet', 'Ranikhet'), ('Dehradun', 'Dehradun'), ('Udhampur', 'Udhampur'), ('Baramula', 'Baramula'), ('Kargil', 'Kargil'), ('Leh', 'Leh'), ('Srinagar', 'Srinagar'), ('Kupwara', 'Kupwara'), ('Allahabad', 'Allahabad'), ('Rajouri', 'Rajouri'), ('Akhnoor', 'Akhnoor'), ('Nagrota', 'Nagrota'), ('Palampur', 'Palampur'), ('Mathura', 'Mathura'), ('Karu', 'Karu')], max_length=255, null=True),
        ),
    ]
