# Generated by Django 5.2.5 on 2025-09-01 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_alter_candidate_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], max_length=20)),
                ('max_theory_marks', models.PositiveIntegerField(default=0)),
                ('max_practical_marks', models.PositiveIntegerField(default=0)),
                ('max_viva_marks', models.PositiveIntegerField(default=0)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_configs', to='exams.trade')),
            ],
        ),
    ]
