# Generated by Django 5.2.5 on 2025-09-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_trade_examconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='marks_obt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
