# Generated by Django 5.2.5 on 2025-09-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_alter_answer_marks_obt'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
