# Generated by Django 5.2.5 on 2025-09-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_candidate_is_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='part',
            field=models.CharField(blank=True, choices=[('A', 'Part A'), ('B', 'Part B'), ('C', 'Part C'), ('D', 'Part D'), ('E', 'Part E'), ('F', 'Part F')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='nsqf_level',
            field=models.FloatField(default=0),
        ),
    ]
