# Generated by Django 5.2.5 on 2025-09-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0016_question_part_alter_candidate_nsqf_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='center',
            field=models.CharField(blank=True, choices=[('SWC-Jaipur', 'SWC-Jaipur'), ('SWC-Hissar', 'SWC-Hissar'), ('SWC-Bathinda', 'SWC-Bathinda'), ('SWC-Sriganganagar', 'SWC-Sriganganagar'), ('SWC-Bikaner', 'SWC-Bikaner'), ('SWC-Suratgarh', 'SWC-Suratgarh'), ('SWC-Kota', 'SWC-Kota'), ('ARTRAC-Port Blair', 'ARTRAC-Port Blair'), ('ARTRAC-Ahmednagar', 'ARTRAC-Ahmednagar'), ('ARTRAC-Bangalore', 'ARTRAC-Bangalore'), ('ARTRAC-Chennai', 'ARTRAC-Chennai'), ('SWC-Pune MINTSD', 'SWC-Pune MINTSD'), ('ARTRAC-MCTE Mhow', 'ARTRAC-MCTE Mhow'), ('SC-Secunderabad', 'SC-Secunderabad'), ('SC-Jhansi', 'SC-Jhansi'), ('SC-Ahmedabad', 'SC-Ahmedabad'), ('SC-Jodhpur', 'SC-Jodhpur'), ('SC-Saugor', 'SC-Saugor'), ('SC-Bhopal', 'SC-Bhopal'), ('SC-Pune', 'SC-Pune'), ('EC-Binaguri', 'EC-Binaguri'), ('EC-Kolkata', 'EC-Kolkata'), ('EC-Missamari', 'EC-Missamari'), ('EC-Rangapahar', 'EC-Rangapahar'), ('EC-Dinjan', 'EC-Dinjan'), ('EC-Gangtok', 'EC-Gangtok'), ('EC-Leimakhong', 'EC-Leimakhong'), ('EC-Tenga', 'EC-Tenga'), ('EC-Panagarh', 'EC-Panagarh'), ('EC-Ranchi', 'EC-Ranchi'), ('EC-Likabali', 'EC-Likabali'), ('EC-Tejpur', 'EC-Tejpur'), ('EC-Kalimpong', 'EC-Kalimpong'), ('WC-Jalandhar', 'WC-Jalandhar'), ('WC-Ambala', 'WC-Ambala'), ('WC-Delhi', 'WC-Delhi'), ('WC-Amritsar', 'WC-Amritsar'), ('WC-Ferozepur', 'WC-Ferozepur'), ('WC-Patiala', 'WC-Patiala'), ('WC-Jammu', 'WC-Jammu'), ('WC-Pathankot', 'WC-Pathankot'), ('WC-Chandimandir', 'WC-Chandimandir'), ('WC-Meerut', 'WC-Meerut'), ('CC-Agra', 'CC-Agra'), ('CC-Bareilly', 'CC-Bareilly'), ('CC-Jabalpur', 'CC-Jabalpur'), ('CC-Lucknow', 'CC-Lucknow'), ('CC-Ranikhet', 'CC-Ranikhet'), ('CC-Dehradun', 'CC-Dehradun'), ('NC-Udhampur', 'NC-Udhampur'), ('NC-Baramula', 'NC-Baramula'), ('NC-Kargil', 'NC-Kargil'), ('NC-Leh', 'NC-Leh'), ('NC-Srinagar', 'NC-Srinagar'), ('NC-Kupwara', 'NC-Kupwara'), ('NC-Allahabad', 'NC-Allahabad'), ('NC-Rajouri', 'NC-Rajouri'), ('NC-Akhnoor', 'NC-Akhnoor'), ('NC-Nagrota', 'NC-Nagrota'), ('NC-Palampur', 'NC-Palampur'), ('NC-Mathura', 'NC-Mathura'), ('NC-Karu', 'NC-Karu')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
