# Generated by Django 5.2.5 on 2025-09-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0018_alter_candidate_trade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='name_of_qualification',
            new_name='primary_qualification',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='duration_of_qualification',
        ),
        migrations.AddField(
            model_name='candidate',
            name='primary_credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='primary_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='secondary_credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='secondary_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='secondary_qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
